[package]
name = "bonsai-starter-methods-guest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fibonacci"
path = "src/bin/fibonacci.rs"

[dependencies]
alloy-primitives = "0.4.2"
alloy-sol-types = "0.4.2"
risc0-zkvm = { version = "0.19.0-rc.1", default-features = false, features = ["std"] }

[profile.release]
lto = true
opt-level = 3

[workspace]
