[package]
name = "bonsai-starter-methods-guest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "is-even"
path = "src/bin/is_even.rs"

[workspace]

[dependencies]
alloy-primitives = { version = "0.6", default-features = false, features = ["rlp", "serde", "std"] }
alloy-sol-types = { version = "0.6" }
risc0-zkvm = { git = "http://github.com/risc0/risc0", rev = "0ab5fd50fc8822e7088a3bf2d2e5bfdcef9ad478", default-features = false, features = ['std'] }

[profile.release]
lto = "thin"
