[workspace]
members = ["methods", "relay"]
resolver = "2"

[workspace.dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", branch = "release-0.18" }
risc0-zkvm = { git = "https://github.com/risc0/risc0", branch = "release-0.18", default-features = false }
bonsai-sdk = { git = "https://github.com/risc0/risc0", branch = "release-0.18" }
bonsai-ethereum-relay = { git = "https://github.com/risc0/risc0", rev = "4652f9c" }
methods = { path = "./methods", package = "bonsai-starter-methods" }

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
