[workspace]
resolver = "2"
members = ["cli", "methods", "sdk"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
alloy-primitives = { version = "0.6", default-features = false, features = ["rlp", "serde", "std"] }
alloy-sol-types = { version = "0.6" }
anyhow = { version = "1.0.75" }
bincode = { version = "1.3" }
bonsai-sdk = { version = "0.6.0" }
bytemuck = { version = "1.14" }
methods = { path = "./methods", package = "bonsai-starter-methods" }
risc0-build = { version = "0.20", features = ["guest-list"] }
risc0-ethereum-sdk = { version = "0.1.0", path = "sdk" }
risc0-zkvm = { version = "0.20", default-features = false }
serde = { version = "1.0", features = ["derive"] }

[profile.release]
debug = 1
lto = true
