[workspace]
resolver = "2"
members = ["apps", "methods"]
exclude = ["lib"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
alloy-primitives = { version = "0.6", default-features = false, features = ["rlp", "serde", "std"] }
alloy-sol-types = { version = "0.6" }
anyhow = { version = "1.0.75" }
bincode = { version = "1.3" }
bonsai-sdk = { version = "0.6.1" }
bytemuck = { version = "1.14" }
ethers = { version = "2.0" }
hex = { version = "0.4" }
log = { version = "0.4" }
methods = { path = "./methods", package = "bonsai-starter-methods" }
# DO NOT MERGE: Figure out what reference to use for this. Cherry pick to the release branch?
risc0-build = { git = "https://github.com/risc0/risc0", rev = "7f73166", features = ["docker"] }
risc0-ethereum-contracts = { git = "https://github.com/risc0/risc0-ethereum" }
risc0-zkvm = { version = "0.20", default-features = false }
risc0-zkp = { version = "0.20", default-features = false }
serde = { version = "1.0", features = ["derive", "std"] }

[profile.release]
debug = 1
lto = true
