[workspace]
resolver = "2"
members = ["apps", "methods"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
alloy-primitives = { version = "0.6", default-features = false, features = ["rlp", "serde", "std"] }
alloy-sol-types = { version = "0.6" }
anyhow = { version = "1.0.75" }
bincode = { version = "1.3" }
bonsai-sdk = { version = "0.6.1" }
bytemuck = { version = "1.14" }
ethers = { version = "2.0" }
hex = { version = "0.4" }
log = { version = "0.4" }
methods = { path = "./methods", package = "bonsai-starter-methods" }
risc0-build = { git = "http://github.com/risc0/risc0", rev = "74c59219f487f6963cff883d69c344088358891f", features = ["guest-list", "docker"] }
risc0-ethereum-contracts = { git = "http://github.com/risc0/risc0-ethereum", rev = "3be9ef901d723e8f3efd4536bcd742f33d6fb16d" }
risc0-zkvm = { git = "http://github.com/risc0/risc0", rev = "74c59219f487f6963cff883d69c344088358891f", default-features = false }
serde = { version = "1.0", features = ["derive", "std"] }

[profile.release]
debug = 1
lto = true
