[workspace]
resolver = "2"
members = ["host", "methods"]

[workspace.dependencies]
host = { path = "host", package = "bonsai-starter-host" }
methods = { path = "./methods", package = "bonsai-starter-methods" }
risc0-build = { version = "0.20.0-rc.2", features = ["guest-list"] }

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
