[workspace]
members = ["methods"]
resolver = "2"

[workspace.dependencies]
risc0-build = "0.19.0-rc.1"
risc0-zkvm = { version = "0.19.0-rc.1", default-features = false }
bonsai-sdk = "0.19.0-rc.1"
methods = { path = "./methods", package = "bonsai-starter-methods" }

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
