[package]
name = "bonsai-starter-methods"
version = { workspace = true }
edition = { workspace = true }

[package.metadata.risc0]
methods = ["guest"]

[build-dependencies]
risc0-build = { workspace = true }

[dependencies]
risc0-build = { workspace = true }

[dev-dependencies]
risc0-zkvm = { workspace = true }
alloy-primitives = { version = "0.6", default-features = false, features = ["rlp", "serde", "std"] }
