[package]
name = "bonsai-starter-methods"
version = "0.1.0"
edition = "2021"

[package.metadata.risc0]
methods = ["guest"]

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", branch = "release-0.15", features = ["guest-list"] }

[dependencies]
bincode = "1.3"
bonsai-sdk = { git = "ssh://git@github.com/risc0/bpn.git", rev = "c047cba3449e333baa300547bbb39d88a119a277" }
bytemuck = "1.13.1"
clap = { version = "4.2.7", features = ["derive"] }
hex = "0.4.3"
risc0-build = { git = "https://github.com/risc0/risc0", branch = "release-0.15", features = ["guest-list"] }
risc0-zkvm = { git = "https://github.com/risc0/risc0", branch = "release-0.15" }
bonsai-sdk-alpha = { package = "bonsai-sdk", git = "https://github.com/risc0/risc0", branch = "parker/bonsai-alpha-sdk" }
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }

[patch.crates-io]
radium = { git = "https://github.com/bitvecto-rs/radium", rev = "723bed5abd75994ee4b7221b8b12c9f4e77ce408" }
