[package]
name = "bonsai-starter-methods"
version = "0.1.0"
edition = "2021"

[package.metadata.risc0]
methods = ["guest"]

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", rev = "0d02111b2f84a53cf6198a0064086b281ed0f749", features = ["guest-list"] }

[dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", rev = "0d02111b2f84a53cf6198a0064086b281ed0f749", features = ["guest-list"] }
risc0-zkvm = { git = "https://github.com/risc0/risc0", rev = "0d02111b2f84a53cf6198a0064086b281ed0f749" }
