[package]
name = "bonsai-starter-methods"
version = "0.1.0"
edition = "2021"

[package.metadata.risc0]
methods = ["guest"]

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", rev = "878580f8a48e6f906a05430f6095d06b1b5ff4d4", features = ["guest-list"] }

[dependencies]
risc0-build = { git = "https://github.com/risc0/risc0", rev = "878580f8a48e6f906a05430f6095d06b1b5ff4d4", features = ["guest-list"] }
risc0-zkvm = { git = "https://github.com/risc0/risc0", rev = "878580f8a48e6f906a05430f6095d06b1b5ff4d4" }
